### ISSUE TITLE
About pre-training on CIFAR-10

### ISSUE THREAD

**Issue by jacobswan1** [chingyaoc/DCL#2]
Hi,
Thanks for your very well organized codes. I'm now trying to reproduce the pre-training on CIFAR-10, while it seems that I might need to tune the hyper-parameters existed in your STL codes. Could you let me know what will be the parameters that needs to be changed for the optimal CIFAR-10 models (say the tau and the training epochs, lr and etc)?  Appreciate your help very much!

**Comment by chingyaoc** [comment]
Hi, I can get similar results with the default hyper-parameters. How many gpu / what batchsize are you using?
